import type { Metadata, Viewport } from 'next';
import Script from 'next/script';

import { Provider } from 'jotai';

import DrawerProvider from '@providers/DrawerProvider';
import ModalProvider from '@providers/modal-provider';
import QueryProvider from '@providers/QueryProvider';

import { Pretendard } from '@utils/fonts';

import '../../build/css/_variables.css';
import './globals.css';

export const viewport: Viewport = {
  width: 'device-width',
  userScalable: false,
  viewportFit: 'cover',
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={Pretendard.variable}>
      <body>
        <QueryProvider>
          <Provider>
            {children}
            <ModalProvider />
            <DrawerProvider />
          </Provider>
        </QueryProvider>
      </body>
      {/* Kakao SDK for JavaScript - v2.7.2 */}
      <Script
        src="https://t1.kakaocdn.net/kakao_js_sdk/2.7.2/kakao.min.js"
        strategy="afterInteractive"
      />
    </html>
  );
}
