import type { Metadata, Viewport } from 'next';

import { Provider } from 'jotai';

import ModalProvider from '@providers/modal-provider';
import QueryProvider from '@providers/QueryProvider';

import { Pretendard } from '@utils/fonts';

import '../../build/css/_variables.css';
import './globals.css';

export const viewport: Viewport = {
  width: 'device-width',
  userScalable: false,
  viewportFit: 'cover',
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={Pretendard.variable}>
      <body>
        <QueryProvider>
          <Provider>
            {children}
            <ModalProvider />
          </Provider>
        </QueryProvider>
      </body>
    </html>
  );
}
