import { DECORATION_TYPE } from '@api/schema/monster';

export const DECORATION_PAIRS = {
  [DECORATION_TYPE.BACKGROUND_COLOR]: [
    // DEFAULT COLOR BG
    '#F450A6', // COLOR_BG_RED
    '#F97D37', // COLOR_BG_ORANGE
    '#FCCB4E', // COLOR_BG_YELLOW
    '#86F45F', // COLOR_BG_GREEN
    '#4485FD', // COLOR_BG_BLUE
    '#8F4FF9', // COLOR_BG_PURPLE
  ],
  [DECORATION_TYPE.CAP]: ['HEADSET'],
  [DECORATION_TYPE.FACE]: ['GLASSES'],
  [DECORATION_TYPE.ACCESSORY]: ['COFFEE', 'LAPTOP', 'PAPER'],
} as const;
